name : CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      # Run CNN Inference
      - name: Run tests
        run: |
          mkdir -p /home/runner/work/classification-pytorch/classification-pytorch/plots
          python3 main.py --mode test --data_path ./data/test/ --model_path ./models/cnn_resnet18_freeze_backbone_False.pth